mysql:
  container_name: mysqlchallenge
  hostname: mysql
  image: mysql/mysql-server:5.7
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: q1w2e3r4
    MYSQL_DATABASE: challenge
    MYSQL_ROOT_HOST: '%'
  ports:
    - 3306:3306

javaClient:
  container_name: javachallenge
  image: maven:3.6.3-jdk-11
  ports:
    - 8080:8080
  volumes:
    - ".:/usr/src/challenge"
  working_dir: /usr/src/challenge
  command: >
    bash -c "mvn clean test install
    && cd target
    && java -jar challenge-0.0.1-SNAPSHOT.jar"
  links:
    - mysql
